config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals
  match "goals/get_account_details" => "goals#get_account_details", :via => :post, :as => 'get_account_details'

  resources :shares
  match "shares/:id/sell_share" => "shares#sell_share", :via => :get, :as => 'sell_share'
  match "shares/:id/complete_share_sale" => "shares#complete_share_sale", :via => :patch, :as => 'complete_share_sale'

  resources :account_transactions

  resources :houses

  get 'tasks/calendar'

  resources :tasks do
    member do
      post :complete_task
      post :complete_task_widget
    end
  end

  get 'admin/index'

  get 'import_transactions/open_file'

  post 'import_transactions/process_file'

  match "import_transactions/:id" => "import_transactions#destroy", :via => :delete, :as => 'destroy_imported_transaction'

  match "import_transactions/:id/transfer" => "import_transactions#transfer", :via => :get, :as => 'transfer_imported_transaction'

  match "import_transactions/:id/update" => "import_transactions#update", :via => :patch, :as => 'imported_transaction'

  get 'import_transactions/import'

  get 'import_transactions/cancel'

  match "import_transactions/:id/split" => "import_transactions#split", :via => :get, :as => 'split_imported_transaction'
  match "import_transactions/add_split" => "import_transactions#add_split", :via => :post, :as => 'add_split_imported_transaction'

  match "import_transactions/:id/tags" => "import_transactions#tags", :via => :get, :as => 'tags_imported_transaction'
  match "import_transactions/add_tags" => "import_transactions#add_tags", :via => :post, :as => 'add_tags_imported_transaction'

  match "import_transactions/:id/flag" => "import_transactions#flag", :via => :get, :as => 'flag_imported_transaction'

  resources :budget_transactions
  match "budget_transactions/:id/edit_budget_item_transaction" => "budget_transactions#edit_budget_item_transaction", :via => :get, :as => 'edit_budget_item_transaction'
  match "budget_transactions/:id/update_cleared_status" => "budget_transactions#update_cleared_status", :via => :get, :as => 'update_cleared_status'
  get 'tags/:tag/:budget_id', to: 'budget_transactions#index', as: :tag
  match "search" => "budget_transactions#index", :via => :post, as: :search

  resources :payees
  post 'payees/select_payee'

  resources :budget_incomes
  match "budget_incomes/:id/show_income_splits" => "budget_incomes#show_income_splits", :via => :get, :as => 'show_income_splits'
  match "budget_incomes/:id/generate_income_splits" => "budget_incomes#generate_income_splits", :via => :post, :as => 'generate_income_splits'

  resources :incomes

  resources :accounts

  resources :account_types

  resources :budgets do
    member do
      post :update_progress
      get :close
    end
  end
  match "budgets/show_or_create/:month" => "budgets#show_or_create", :via => :get, :as => 'show_or_create_budget'

  resources :budget_items, :only => [:edit,:show,:update]
  match "budget_items/:id/one_click_transaction" => "budget_items#one_click_transaction", :via => :post, :as => 'one_click_transaction'

  resources :dashboard, :only => [:index]

  resources :categories
  match "categories/:id/edit_transaction_category" => "categories#edit_transaction_category", :via => :get, :as => 'edit_transaction_category'
  post 'categories/select_transaction_category'

  resources :master_categories

  get 'loans/index'

  get 'reports/index'
  get 'reports/category_report'
  get 'reports/master_category_report'
  get 'reports/payee_report'
  get 'reports/budget_expense_report'
  get 'reports/timeline'

  root 'dashboard#index'

end

app/controllers/budget_transactions_controller.rb
class BudgetTransactionsController < ApplicationController
  before_action :set_budget_transaction, only: [:show, :edit, :update, :destroy, :edit_budget_item_transaction, :update_cleared_status]
respond_to :js, :html
  # GET /budget_transactions
  # GET /budget_transactions.json
  def index
    puts params[:tag]
    if !params[:tag].nil?
      @tag = params[:tag]
      @budget_transactions = BudgetTransaction.tagged_with(@tag,:any => true)

      if params[:budget_id]
        @budget = Budget.find(params[:budget_id])
      end
    elsif !params[:budget_id].nil? && !params[:account_id].nil?
      @budget = Budget.find(params[:budget_id])
      @account = Account.find(params[:account_id])
      @budget_transactions = BudgetTransaction.where('budget_id =? and account_id = ?',@budget.id,@account.id)
      @budget_withdrawals = BudgetTransaction.where('budget_id = ? and payee_id = ?',@budget.id, @account.payee.id)
    elsif !params[:budget_id].nil?
      @budget = Budget.find(params[:budget_id])
      @budget_transactions = @budget.budget_transactions
    else
      @budget_transactions = BudgetTransaction.all
    end
  end

  # GET /budget_transactions/1
  # GET /budget_transactions/1.json
  def show
  end

  # GET /budget_transactions/new
  def new
    @budget_transaction = BudgetTransaction.new
    @budget_transaction.budgeted = false
    @budget_transaction.scheduled = false
    @budget_transaction.manual = true

    if !params[:budget_id].nil?
      @budget_transaction.budget_id = params[:budget_id].to_i
    elsif !session[:budget_id].nil?
      @budget_transaction.budget_id = session[:budget_id]
    else
      budget = Budget.where('start_date <= ? and end_date >= ?',Date.today,Date.today).first
      unless budget.nil?
        @budget_transaction.budget_id = budget.id
      end
    end

    #TODO
    # This block can be deprecated
    if params[:tranasction_type] === "miscellaneous"
      @budget_transaction.miscellaneous = true
      @budget_transaction.savings = false
    elsif params[:tranasction_type] === "savings"
      @budget_transaction.miscellaneous = false
      @budget_transaction.savings = true
    end
  end

  # GET /budget_transactions/1/edit
  def edit
    @transaction_type = params[:transaction_type]

    respond_to do |format|
        format.js
    end
  end

  # GET /budget_transactions/1/edit_budget_item_transaction
  def edit_budget_item_transaction
    respond_to do |format|
        format.js
    end
  end

  # POST /budget_transactions
  # POST /budget_transactions.json
  def create
    @budget_transaction = BudgetTransaction.new(budget_transaction_params)

    if @budget_transaction.transaction_type == 'loan_transfer'
      @budget_transaction.category_id = Category.find_by_name("Lending").id
    else
      @budget_transaction.category_id = @budget_transaction.payee.category.id
    end

    if budget_transaction_params[:historical_loan_transaction] == "1" || budget_transaction_params[:historical_account_transaction] == "1"
      @budget_transaction.historical = true
    end

    if @budget_transaction.credit.nil?
      @budget_transaction.credit = 0.00
    end
    if @budget_transaction.debit.nil?
      @budget_transaction.debit = 0.00
    end

    # Set budget Item for non-budgeted transactions. This is for BudgetItems only
    if @budget_transaction.budget_item.nil?
      if !@budget_transaction.transaction_type.nil? && @budget_transaction.transaction_type == 'miscellaneous'
        @budget_item = BudgetItem.find_by_budget_id_and_category_id(
          @budget_transaction.budget.id,Category.find_by_miscellaneous_and_mandatory(true,true).id)
        @budget_transaction.budget_item = @budget_item
      end
    else
      @budget_item = @budget_transaction.budget_item
    end

    # Determine Misc vs Savings Transaction
    # unless @budget_transaction.budgeted
    #   if !@budget_transaction.transaction_type.nil? && @budget_transaction.transaction_type == 'miscellaneous'
    #     @budget_transaction.miscellaneous = true
    #     @budget_transaction.savings = false
    #   elsif !@budget_transaction.transaction_type.nil? && @budget_transaction.transaction_type == 'savings'
    #     @budget_transaction.miscellaneous = false
    #     @budget_transaction.savings = true
    #   end
    # end

    respond_to do |format|
      if @budget_transaction.save
        format.html { redirect_to @budget_transaction.budget, notice: 'Budget transaction was successfully created.' }
        format.json { render :show, status: :created, location: @budget_transaction }
        format.js
      else
        format.html { render :new }
        format.json { render json: @budget_transaction.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /budget_transactions/1
  # PATCH/PUT /budget_transactions/1.json
  def update
    @budget_transaction.category_id = @budget_transaction.payee.category.id
    @budget_item = @budget_transaction.budget_item

    # Determine Misc vs Savings Transaction
    # unless @budget_transaction.budgeted
    #   if !@budget_transaction.transaction_type.nil? && @budget_transaction.transaction_type == 'miscellaneous'
    #     @budget_transaction.miscellaneous = true
    #     @budget_transaction.savings = false
    #   elsif !@budget_transaction.transaction_type.nil? && @budget_transaction.transaction_type == 'savings'
    #     @budget_transaction.miscellaneous = false
    #     @budget_transaction.savings = true
    #   end
    # end

    respond_to do |format|
      if @budget_transaction.update(budget_transaction_params)
        format.js
        format.html { redirect_to @budget_transaction.budget, notice: 'Budget transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget_transaction }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @budget_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_transactions/1
  # DELETE /budget_transactions/1.json
  def destroy
    @budget_item = @budget_transaction.budget_item
    @budget_transaction.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to @budget_item.budget, notice: 'Budget transaction was successfully destroyed.' }
    end
  end

  def update_cleared_status
    reconciled = @budget_transaction.reconciled
    is_payee_account = params[:is_payee_account]

    @budget_transaction.update_attributes!(:reconciled => !reconciled)

    respond_to do |format|
      @budget = @budget_transaction.budget
      @account = @budget_transaction.account
      if is_payee_account == 'true'
        @budget_transactions = BudgetTransaction.where('budget_id =? and account_id = ?',@budget.id,@budget_transaction.payee.account.id)
        @budget_withdrawals = BudgetTransaction.where('budget_id = ? and payee_id = ?',@budget.id, @account.id)
      else
        @budget_transactions = BudgetTransaction.where('budget_id =? and account_id = ?',@budget.id,@account.id)
        @budget_withdrawals = BudgetTransaction.where('budget_id = ? and payee_id = ?',@budget.id, @account.payee.id)
      end
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget_transaction
      @budget_transaction = BudgetTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_transaction_params
      params.require(:budget_transaction).permit(:credit, :debit, :transaction_date, :comments, :manual, :scheduled, :budgeted,
        :miscellaneous, :savings, :account_id, :budget_item_id, :budget_id,:payee_id,:category_id,:transaction_type,:reconciled,
        :tag_list,:flagged,:historical_loan_transaction,:historical_account_transaction,:historical,:account_transfer,:loan,:share,:house,:superannuation,:mortgage_interest)
    end
end

app/helpers/budget_transactions_helper.rb
module BudgetTransactionsHelper
end

app/views/budget_transactions/_edit.html.erb
<!-- Modal -->
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h4 class="modal-title" id="newTransactionModalLabel">Edit <%=@transaction_type%> Transaction</h4>
		</div>

		<div class="modal-body">
			<div class="panel panel-default">
				<div>
					<div class="panel-body">
							<h3><span class="fa fa-pencil"></span> Edit <%=@transaction_type%> Transaction</h3>
							<p>Edit <%=@transaction_type%> transaction for current budget month.</p>
					</div>
					<div class="panel-body form-group-separated">
						<%= form_for @budget_transaction, format: :html, html: {class: "form-horizontal", role: :form} do |f| %>
						<%= f.hidden_field :budgeted ,:value => @budget_transaction.budgeted%>
						<%= f.hidden_field :scheduled, :value => @budget_transaction.scheduled%>
						<%= f.hidden_field :miscellaneous, :value => @budget_transaction.miscellaneous%>
						<%= f.hidden_field :savings, :value => @budget_transaction.savings%>
						<%= f.hidden_field :budget_id, :value => @budget_transaction.budget.id%>
						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Account</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group">
											<%if @transaction_type == 'miscellaneous'%>
												<%= f.collection_select :account_id, Account.for_budget.active, :id, :name, {prompt: true}, {class: "form-control select", disabled: true} %>
											<%elsif @transaction_type == 'account_transfer'%>
												<%= f.collection_select :account_id, Account.for_transfer.active, :id, :name, {prompt: true}, {class: "form-control select", disabled: true} %>
											<%else%>
												<%= f.collection_select :account_id, Account.goal_account.active, :id, :name, {prompt: true}, {class: "form-control select", disabled: true} %>
											<%end%>
										</div>
								</div>
						</div>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">
									<%if @transaction_type == 'miscellaneous'%>
										Payee
									<%elsif @transaction_type == 'savings' || @transaction_type == 'account_transfer'%>
										From
									<%elsif @transaction_type == 'savings_expense'%>
										Payee
									<%end%>
								</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group">
											<%if @transaction_type == 'miscellaneous'%>
												<%= f.collection_select :payee_id, Payee.external_payees, :id, :name, {prompt: true}, {class: "form-control select", disabled: true} %>
											<%elsif @transaction_type == 'savings'%>
												<%= f.collection_select :payee_id, Payee.non_credit_account_payees, :id, :name, {prompt: true}, {class: "form-control select", disabled: true} %>
											<%elsif @transaction_type == 'account_transfer'%>
												<%= f.collection_select :payee_id, Payee.transfer_account_payees, :id, :name, {prompt: true}, {class: "form-control select", disabled: true} %>
											<%elsif @transaction_type == 'savings_expense'%>
												<%= f.collection_select :payee_id, Payee.external_payees + Payee.account_payees, :id, :name, {prompt: true}, {class: "form-control select", disabled: true} %>
											<%end%>
										</div>
								</div>
						</div>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Transaction Date</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group date">
												<%= f.text_field :transaction_date, class: "form-control datepicker",value: @budget_transaction.transaction_date %>
												<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
										</div>
								</div>
						</div>

						<%unless @transaction_type == 'savings' || @transaction_type == 'account_transfer'%>
						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Debit</label>
								<div class="col-md-9 col-xs-7">
									<div class="input-group">
										<%= f.number_field :debit, step: :any, class: "form-control" %>
										<span class="input-group-addon"><span class="fa fa-usd"></span></span>
									</div>
								</div>
						</div>
						<%end%>

						<%unless @transaction_type == 'savings_expense' || @transaction_type == 'mortgage'%>
						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Credit</label>
								<div class="col-md-9 col-xs-7">
									<div class="input-group">
										<%= f.number_field :credit, step: :any, class: "form-control" %>
										<span class="input-group-addon"><span class="fa fa-usd"></span></span>
									</div>
								</div>
						</div>
						<%end%>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Comments</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group">
												<%= f.text_field :comments, class: "form-control" %>
												<span class="input-group-addon"><span class="fa fa-comment"></span></span>
										</div>
								</div>
						</div>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Tags</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group">
												<%= f.text_field :tag_list, 'data-role'=>'tagsinput', class: "form-control" %>
												<span class="input-group-addon"><span class="fa fa-tags"></span></span>
										</div>
								</div>
						</div>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Cleared?</label>
								<div class="col-md-9 col-xs-7">
									<label class="switch">
										<%= f.check_box :reconciled%>
										<span></span>
									</label>
								</div>
						</div>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Flagged?</label>
								<div class="col-md-9 col-xs-7">
									<label class="switch">
										<%= f.check_box :flagged%>
										<span></span>
									</label>
								</div>
						</div>
						<%if @transaction_type == 'mortgage'%>
							<div class="form-group">
									<label class="col-md-3 col-xs-5 control-label">Interest Charged</label>
									<div class="col-md-9 col-xs-7">
										<div class="input-group">
											<%= f.number_field :mortgage_interest, step: :any, class: "form-control" %>
											<span class="input-group-addon"><span class="fa fa-usd"></span></span>
										</div>
									</div>
							</div>
						<%end%>
						<div class="form-group">
								<div class="col-md-12 col-xs-5">
										<%= f.submit class: "btn btn-primary btn-rounded pull-right" %>
								</div>
						</div>
						<%end%>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>

	</div>
</div>
<script>
$(function() {
    $( ".datepicker").datepicker({dateFormat: 'dd-mm-yy' });
  });

$(function() {
	$("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput({
		tagClass: 'label fa fa-tag'
	});
});

$(function() {
  $('#new-budgeted-transaction-button').click(function(event){
    $('#new-budgeted-transaction-row').slideDown(1000);
  });
});
</script>

app/views/budget_transactions/_transactions_list.html.erb
<div id="transaction-details-pane">
		<div id="import-preview-pane-content">
			<table class="table table-striped table-bordered">
				<thead>
					<th style="width: 10%;">Payee</th>
					<th style="width: 10%;">Category</th>
					<th style="width: 10%;">Budget Category</th>
					<th style="width: 10%;">Date</th>
					<th style="width: 20%;">Description</th>
					<th style="width: 10%">Credit</th>
					<th style="width: 10%;">Debit</th>
					<th style="width: 18%;">Tags</th>
					<th style="width: 2%;">Cleared</th>
				</thead>
				<!--Budget Transactions-->
				<%@budget_transactions.each do |txn|%>
					<tr>
						<td style="width: 10%;padding-left: 5px !important;">
							<%=txn.payee.name unless txn.payee.nil?%>
						</td>
						<td style="width: 10%;"><%=txn.category.name unless txn.category.nil?%></td>
						<td style="width: 10%;"><%=txn.budget_item.category.name unless txn.budget_item_id.nil?%></td>
						<td style="width: 10%;"><%=txn.transaction_date%></td>
						<td style="width: 30%;"><%=txn.comments%></td>
						<td style="width: 10%;text-align: right;">
							<%unless txn.credit == 0%>
								<%=number_to_currency(txn.credit, precision: 2)%>
							<%end%>
						</td>
						<td style="width: 10%;text-align: right;">
							<%unless txn.debit == 0%>
								<%=number_to_currency(txn.debit, precision: 2)%>
							<%end%>
						</td>
						<td  style="width: 18%;text-align: right;">
							<ul class="list-tags">
							<%txn.tags.each do|tag|%>
								<li>
								<%= link_to tag_path(tag.name,txn.budget.id) do %>
									<span class="fa fa-tag"></span><%=tag.name%>
								<%end%>
								</li>
							<%end%>
						</ul>
						</td>
						<td style="width: 2%;border-right: none;text-align: center;">
							<%=link_to update_cleared_status_path(txn,is_payee_account: false), :remote => true do%>
								<%if txn.reconciled%>
									<%=image_tag 'cleared-icon.png'%>
								<%else%>
									<%=image_tag 'uncleared-icon.png'%>
								<%end%>
							<%end%>
						</td>
					</tr>
				<%end%>

				<!--Budget Withdrawals-->
				<%unless @account.nil?%>
					<%@budget_withdrawals.each do |wtxn|%>
						<tr>
							<td style="width: 10%;padding-left: 5px !important;">
								<%=wtxn.account.name unless wtxn.account.nil?%>
							</td>
							<td style="width: 10%;">
								<%=wtxn.category.name unless wtxn.category.nil?%>
								<%if wtxn.category.name == 'Account Transfer' || wtxn.category.name == 'Lending'%>
									<span class='glyphicon glyphicon-transfer' style='color: #999;' aria-hidden='true'></span>
								<%end%>
							</td>
							<td style="width: 10%;"><%=wtxn.transaction_date%></td>
							<td style="width: 40%;"><%=wtxn.comments%></td>

							<!-- Debit and Credit swapped around as this is for payees-->
							<td style="width: 10%;text-align: right;">
								<%unless wtxn.debit == 0%>
									<%=number_to_currency(wtxn.debit, precision: 2)%>
								<%end%>
							</td>
							<td style="width: 10%;text-align: right;">
								<%unless wtxn.credit == 0%>
									<%=number_to_currency(wtxn.credit, precision: 2)%>
								<%end%>
							</td>
							<!-- =====================================================-->
							<td  style="width: 18%;text-align: right;">
								<ul class="list-tags">
								<%wtxn.tags.each do|wtag|%>
									<li>
									<%= link_to tag_path(wtag.name,wtxn.budget.id) do %>
										<span class="fa fa-tag"></span><%=wtag.name%>
									<%end%>
									</li>
								<%end%>
							</ul>
							</td>
							<td style="width: 5%;border-right: none;text-align: right;">
								<%=link_to update_cleared_status_path(wtxn,is_payee_account: true), :remote => true do%>
									<%if wtxn.reconciled%>
										<%=image_tag 'cleared-icon.png'%>
									<%else%>
										<%=image_tag 'uncleared-icon.png'%>
									<%end%>
								<%end%>
							</td>
							<td style="width: 5%;">
								<div class="actions">
									Actions
								</div>
							</td>
						</tr>
					<%end%>
				<%end%>
			</table>
		</div>

		<div id="import-preview-footer">
			<div class="col-md-1" style="margin-left: -10px;">
				&nbsp;
			</div>
			<div class="col-md-10">
				<div id="import-totals-content">
					<%

						credit = @budget_transactions.sum(:credit)
						debit = @budget_transactions.sum(:debit)

						reconciled_total = (@budget_transactions.reconciled_transactions.sum(:credit))- (@budget_transactions.reconciled_transactions.sum(:debit))

						nonconciled_total = (@budget_transactions.nonconciled_transactions.sum(:credit) )- (@budget_transactions.nonconciled_transactions.sum(:debit))

						unless @account.nil?
							credit = @budget_transactions.sum(:credit) + @budget_withdrawals.sum(:debit)
							debit = @budget_transactions.sum(:debit) + @budget_withdrawals.sum(:credit)

							reconciled_total = (@budget_transactions.reconciled_transactions.sum(:credit) + @budget_withdrawals.reconciled_transactions.sum(:debit))- (@budget_transactions.reconciled_transactions.sum(:debit)+@budget_withdrawals.reconciled_transactions.sum(:credit))

							nonconciled_total = (@budget_transactions.nonconciled_transactions.sum(:credit) + @budget_withdrawals.nonconciled_transactions.sum(:debit))- (@budget_transactions.nonconciled_transactions.sum(:debit)+@budget_withdrawals.nonconciled_transactions.sum(:credit))

						end
					%>
					<table style="width:100%;height: 100%;">
						<tr>
							<td style="width: 15%;">Credit</td>
							<td>&nbsp;</td>
							<td style="width: 15%;">Debit</td>
							<td>&nbsp;</td>
							<td style="width: 15%">Balance</td>
							<td style="border-left: 1px dotted #333;">&nbsp;</td>
							<td style="width: 15%;">Cleared Balance</td>
							<td>&nbsp;</td>
							<td style="width: 15%;">Uncleared Transactions</td>
							<td>&nbsp;</td>
							<td style="width: 15%;">Working Balance</td>
						</tr>
						<tr style="font-size: 14px;">
							<td><%=number_to_currency(credit, precision: 2)%></td>
							<td>-</td>
							<td><%=number_to_currency(debit, precision: 2)%></td>
							<td>=</td>
							<td>
							<%=number_to_currency(credit - debit, precision: 2)%>
							</td>
							<td style="border-left: 1px dotted #333;">&nbsp;</td>
							<td>
								<%=number_to_currency(reconciled_total, precision: 2)%>
							</td>
							<td>+</td>
							<td style="color: red;">
								<%=number_to_currency(nonconciled_total, precision: 2)%>
							</td>
							<td>=</td>
							<td><%=number_to_currency(reconciled_total + nonconciled_total, precision: 2)%></td>
						</tr>
					</table>
				</div>
			</div>
			<div class="col-md-1">
				<%= link_to "Back",@budget, class: "btn btn-primary btn-lg", style: "height: 100%;"%>
			</div>
		</div>
</div>

app/views/budget_transactions/create.js.erb
$("#budget-transactions-list").replaceWith("<%= escape_javascript(render '/budget_transactions/budget_transactions_list',:locals => {:obj => @budget_item}) %>");

app/views/budget_transactions/edit.html.erb
<h1>Editing budget_transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget_transaction %> |
<%= link_to 'Back', budget_transactions_path %>

app/views/budget_transactions/edit.js.erb
$("#newTransactionModal").html("<%= escape_javascript(render '/budget_transactions/edit') %>");
$('#newTransactionModal').modal('show');

app/views/budget_transactions/new.html.erb
<h1>New budget_transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', budget_transactions_path %>

app/views/budget_transactions/new.js.erb
$("#newTransactionModal").html("<%= escape_javascript(render '/budget_transactions/new') %>");
$('#newTransactionModal').modal('show');

app/views/budget_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Credit:</strong>
  <%= @budget_transaction.credit %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @budget_transaction.debit %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @budget_transaction.transaction_date %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @budget_transaction.comments %>
</p>

<p>
  <strong>Manual:</strong>
  <%= @budget_transaction.manual %>
</p>

<p>
  <strong>Scheduled:</strong>
  <%= @budget_transaction.scheduled %>
</p>

<p>
  <strong>Budgeted:</strong>
  <%= @budget_transaction.budgeted %>
</p>

<p>
  <strong>Account:</strong>
  <%= @budget_transaction.account_id %>
</p>

<p>
  <strong>Budget item:</strong>
  <%= @budget_transaction.budget_item_id %>
</p>

<p>
  <strong>Payee:</strong>
  <%= @budget_transaction.payee_id %>
</p>

<%= link_to 'Edit', edit_budget_transaction_path(@budget_transaction) %> |
<%= link_to 'Back', budget_transactions_path %>

app/views/budget_transactions/update.js.erb
$("#budget-transactions-list").replaceWith("<%= escape_javascript(render '/budget_transactions/budget_transactions_list',:locals => {:obj => @budget_item}) %>");

app/views/budget_transactions/update_cleared_status.js.erb
$("#transaction-details-pane").replaceWith("<%= escape_javascript(render 'transactions_list') %>");