config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals
  match "goals/get_account_details" => "goals#get_account_details", :via => :post, :as => 'get_account_details'

  resources :shares
  match "shares/:id/sell_share" => "shares#sell_share", :via => :get, :as => 'sell_share'
  match "shares/:id/complete_share_sale" => "shares#complete_share_sale", :via => :patch, :as => 'complete_share_sale'

  resources :account_transactions

  resources :houses

  get 'tasks/calendar'

  resources :tasks do
    member do
      post :complete_task
      post :complete_task_widget
    end
  end

  get 'admin/index'

  get 'import_transactions/open_file'

  post 'import_transactions/process_file'

  match "import_transactions/:id" => "import_transactions#destroy", :via => :delete, :as => 'destroy_imported_transaction'

  match "import_transactions/:id/transfer" => "import_transactions#transfer", :via => :get, :as => 'transfer_imported_transaction'

  match "import_transactions/:id/update" => "import_transactions#update", :via => :patch, :as => 'imported_transaction'

  get 'import_transactions/import'

  get 'import_transactions/cancel'

  match "import_transactions/:id/split" => "import_transactions#split", :via => :get, :as => 'split_imported_transaction'
  match "import_transactions/add_split" => "import_transactions#add_split", :via => :post, :as => 'add_split_imported_transaction'

  match "import_transactions/:id/tags" => "import_transactions#tags", :via => :get, :as => 'tags_imported_transaction'
  match "import_transactions/add_tags" => "import_transactions#add_tags", :via => :post, :as => 'add_tags_imported_transaction'

  match "import_transactions/:id/flag" => "import_transactions#flag", :via => :get, :as => 'flag_imported_transaction'

  resources :budget_transactions
  match "budget_transactions/:id/edit_budget_item_transaction" => "budget_transactions#edit_budget_item_transaction", :via => :get, :as => 'edit_budget_item_transaction'
  match "budget_transactions/:id/update_cleared_status" => "budget_transactions#update_cleared_status", :via => :get, :as => 'update_cleared_status'
  get 'tags/:tag/:budget_id', to: 'budget_transactions#index', as: :tag
  match "search" => "budget_transactions#index", :via => :post, as: :search

  resources :payees
  post 'payees/select_payee'

  resources :budget_incomes
  match "budget_incomes/:id/show_income_splits" => "budget_incomes#show_income_splits", :via => :get, :as => 'show_income_splits'
  match "budget_incomes/:id/generate_income_splits" => "budget_incomes#generate_income_splits", :via => :post, :as => 'generate_income_splits'

  resources :incomes

  resources :accounts

  resources :account_types

  resources :budgets do
    member do
      post :update_progress
      get :close
    end
  end
  match "budgets/show_or_create/:month" => "budgets#show_or_create", :via => :get, :as => 'show_or_create_budget'

  resources :budget_items, :only => [:edit,:show,:update]
  match "budget_items/:id/one_click_transaction" => "budget_items#one_click_transaction", :via => :post, :as => 'one_click_transaction'

  resources :dashboard, :only => [:index]

  resources :categories
  match "categories/:id/edit_transaction_category" => "categories#edit_transaction_category", :via => :get, :as => 'edit_transaction_category'
  post 'categories/select_transaction_category'

  resources :master_categories

  get 'loans/index'

  get 'reports/index'
  get 'reports/category_report'
  get 'reports/master_category_report'
  get 'reports/payee_report'
  get 'reports/budget_expense_report'
  get 'reports/timeline'

  root 'dashboard#index'

end

app/controllers/import_transactions_controller.rb
class ImportTransactionsController < ApplicationController
  require 'csv'

  def open_file
    @budget = Budget.find(params[:budget_id])
  end

  def process_file
    @budget = Budget.find(params[:budget_id])
    session[:budget_id] = @budget.id

    ImportedTransaction.destroy_all
    account = Account.find(params[:account_id])
    txn_budget = Budget.find(params[:transaction_budget_id])
    import_balance_due = params[:import_balance_due]
    first_row = true

    CSV.foreach(params[:file].path, headers: false) do |row|
      imported_transaction, txn_date, txn_amount, txn_description, txn_balance,txn_date_format, payee, credit, debit, category_id, payee_id = nil

      unless account.import_txn_date_col.nil?
        txn_date = row[account.import_txn_date_col] unless account.import_txn_date_col.nil?
        txn_amount = row[account.import_txn_amount_col]
        txn_description = row[account.import_txn_description_col]
        txn_balance = row[account.import_txn_balance_col] unless account.import_txn_balance_col.nil?
        txn_date_format = account.import_txn_date_format

        payeeDescription = PayeeDescription.find_by_description(txn_description)
        unless payeeDescription.nil?
          payee = payeeDescription.payee
        end

        unless payee.nil?
          payee_id = payee.id
          category_id= payee.category.id
        end

        if account.is_debit_negetive
          if txn_amount.to_f > 0
            credit = txn_amount.to_f
          else
            debit = txn_amount.to_f
          end
        else
          if txn_amount.to_f > 0
            debit = txn_amount.to_f * -1
          else
            credit = txn_amount.to_f.abs
          end
        end

        imported_transaction = ImportedTransaction.new(raw_data: row.to_s, credit: credit, debit: debit, txn_date: Date.strptime(txn_date.to_s,txn_date_format.to_s),
         description: txn_description, balance: txn_balance, account_id: account.id, payee_id: payee_id, category_id: category_id,budget_id: txn_budget.id)

        budget_transaction = BudgetTransaction.find_by_raw_data(row.to_s)

        if first_row && imported_transaction.balance.nil? && !import_balance_due.nil?
          imported_transaction.balance = import_balance_due.to_f * -1
          first_row = false
        end

        if budget_transaction.nil? && !imported_transaction.nil?
          imported_transaction.save!

        end
      end
    end
  end

  def transfer
    @imported_transaction = ImportedTransaction.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def split
    @imported_transaction = ImportedTransaction.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def add_split
    imported_transaction = ImportedTransaction.find(params[:txn_id])
    credit = params[:credit]
    debit = params[:debit]
    category = params[:category_id]

    begin
      ImportedTransaction.transaction do

        if (category.nil?)
          raise 'Category cannot be blank. Please select or add a new payee.'
        end

        split_transaction = ImportedTransaction.new(raw_data: nil, credit: credit, debit: debit, txn_date: imported_transaction.txn_date,
         description: imported_transaction.description, balance: nil, account_id: imported_transaction.account.id, payee_id: imported_transaction.payee.id, category_id: category,budget_id: imported_transaction.budget_id)

        split_transaction.save!

        unless(credit.nil?)
          imported_transaction.credit = imported_transaction.credit - credit.to_f
        end

        unless(debit.nil?)
          imported_transaction.debit = imported_transaction.debit - debit.to_f
        end

        imported_transaction.save!

        respond_to do |format|
          format.js
        end
      end
    rescue => e
      puts e.message
      @imported_transactions = ImportedTransaction.all
      render :process_file
    end

  end

  def tags
    @imported_transaction = ImportedTransaction.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def add_tags
    @imported_transaction = ImportedTransaction.find(params[:txn_id])

    unless params[:tags].nil?
      puts 'entering tags add'
      @imported_transaction.tags = params[:tags]
      puts @imported_transaction.tags
      @imported_transaction.save!
    end

    respond_to do |format|
      format.js { render '/import_transactions/preview'}
    end

  end

  def flag
    @imported_transaction = ImportedTransaction.find(params[:id])
    if @imported_transaction.flagged?
      @imported_transaction.flagged = false
    else
      @imported_transaction.flagged = true
    end

    respond_to do |format|
      @imported_transaction.save!
      format.js
    end
  end

  def update
    @imported_transaction = ImportedTransaction.find(params[:id])
    @imported_transaction.account_id = params[:imported_transaction][:account_id]
    @imported_transaction.payee_id = params[:imported_transaction][:payee_id]

    unless @imported_transaction.payee_id.nil?
      payee = Payee.find(@imported_transaction.payee_id)
      unless payee.nil?
        @imported_transaction.category_id = payee.category_id
      end
    end

    @imported_transaction.save!

    respond_to do |format|
      format.js { render '/import_transactions/preview'}
    end
  end

  def destroy
    imported_transaction = ImportedTransaction.find(params[:id])
    imported_transaction.destroy

    respond_to do |format|
      format.js { render '/import_transactions/preview'}
    end
  end

  def import
    unless session[:budget_id].nil?
      @budget = Budget.find(session[:budget_id])
    end

    begin
      ImportedTransaction.transaction do
        ImportedTransaction.all.each do |txn|
          misc = false
          is_budgeted = false
          budget_item_id = nil
          credit_val = 0.00
          debit_val = 0.00

          if (txn.payee.nil?)
            raise 'Payee cannot be blank. Please select or add a new payee.'
          end

          unless (txn.raw_data.nil?)
            existing_budget_transaction = BudgetTransaction.find_by_raw_data(txn.raw_data)
            unless (existing_budget_transaction.nil?)
              raise 'Duplicate transaction import detected. txn: ' + txn.raw_data.to_s
            end
          end

          unless (txn.credit.nil?)
            credit_val = txn.credit.abs
          end

          unless (txn.debit.nil?)
            debit_val = txn.debit.abs
          end
          # budget = Budget.get_budget(txn.txn_date)
          budget = Budget.find(txn.budget_id)
          category = Category.find(txn.category.id)
          budget_item = BudgetItem.find_by_budget_id_and_category_id(budget.id,category.id)

          if budget_item.nil?
            budget_item = BudgetItem.find_by_budget_id_and_category_id(budget.id,Category.find_by_miscellaneous_and_mandatory(true,true).id)
          end

          if category.miscellaneous
            misc = true
          elsif category.budgeted
            is_budgeted = true
          end

          unless budget_item.nil?
            budget_item_id = budget_item.id
          end

          budget_txn = BudgetTransaction.new(account_id: txn.account_id,budget_item_id: budget_item_id,payee_id: txn.payee_id,
            budget_id: budget.id,category_id: txn.category_id, credit: credit_val, debit: debit_val,
            transaction_date: txn.txn_date,comments: txn.description,raw_data:txn.raw_data ,
            manual: false, scheduled: false, budgeted: is_budgeted,miscellaneous: misc,savings: false,reconciled: false,tag_list: txn.tags,flagged: txn.flagged)

          budget_txn.save!
          txn.budget_id = budget.id
          txn.save!
          # txn.destroy
        end
        # raise 'Test error'
        # redirect_to budgets_path
      end
    rescue => e
      flash.now[:error] = "Imported transactions could not be saved: #{e.message}"
      @imported_transactions = ImportedTransaction.all
      render :process_file
    end
  end

  def cancel
    ImportedTransaction.destroy_all

    redirect_to budgets_path
  end
end

app/helpers/import_transactions_helper.rb
module ImportTransactionsHelper
end

app/views/import_transactions/_open_file.html.erb
<!-- Modal -->
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h4 class="modal-title" id="importTransactionModalLabel">Import Transactions</h4>
		</div>
		<div class="modal-body">
			<%= form_tag import_transactions_process_file_path, multipart: true, class: "form-horizontal" do %>
			<div class="panel panel-default">
				<div class="panel-body">
						<h3><span class="fa fa-download"></span> Import Trasactions</h3>
						<p>Import transactions from bank statements in CSV format.</p>
				</div>

				<div class="panel-body form-group-separated">
					<%= hidden_field_tag :budget_id, @budget.id%>
					<div class="form-group">
							<label class="col-md-3 col-xs-5 control-label">Import for Budget</label>
							<div class="col-md-9 col-xs-7">
								<%= select_tag :transaction_budget_id, options_from_collection_for_select(Budget.all.open_budgets, :id, :name)%>
							</div>
					</div>
					<div class="form-group">
							<label class="col-md-3 col-xs-5 control-label">Import for Account</label>
							<div class="col-md-9 col-xs-7">
								<%= select_tag :account_id, options_from_collection_for_select(Account.credit_account.active.all, :id, :name)%>
							</div>
					</div>
					<div class="form-group">
							<label class="col-md-3 col-xs-5 control-label">Balance Due</label>
							<div class="col-md-9 col-xs-7">
								<%= number_field_tag :import_balance_due, nil, :step => 0.01 %>
							</div>
					</div>
					<div class="form-group">
							<label class="col-md-3 col-xs-5 control-label">File</label>
							<div class="col-md-9 col-xs-7">
								<%= file_field_tag :file,class: "btn btn-primary btn-file" %>
							</div>
					</div>

					<div class="form-group">
							<div class="col-md-12 col-xs-5">
								<%= button_tag(type: 'submit', class: "btn btn-primary pull-right") do %>
								 <i class='fa fa-download'></i>&nbsp;Import
								<% end %>
							</div>
					</div>
				</div>
			</div>
			<%end%>

		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</div>
</div>

app/views/import_transactions/_preview.html.erb
<div id="import-preview-pane">
  <script type="text/javascript">
    $(document).ready(function() {
      table = $('#import-txn-table').DataTable( {
        retrieve: true,
        paging: false
      } );
    } );
    </script>
  <%if ImportedTransaction.all.count < 1%>
    <div style="font-size: 13px;" class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign"></span>
      The are no transactions to import.
    </div>
    <div style="text-align: right;">
      <%= link_to "Close",import_transactions_cancel_path(), class: "btn btn-default", style: "height: 100%;"%>
    </div>
  <%else%>
    <%non_payee_txns = ImportedTransaction.where("payee_id IS NULL").count%>
    <%if non_payee_txns > 0%>
    <div style="font-size: 13px;" class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign"></span> <strong>Warning!</strong>
      <%=non_payee_txns%> transactions do not have a Payee. Please add Payees.
    </div>
    <%end%>
    <div class="panel panel-default">
        <div class="panel-body">


    <div id="import-preview-pane-content" class="table-responsive">
      <table id="import-txn-table" class="table table-striped table-bordered datatable">
        <thead>
          <tr>
            <th style="width: 10%;">Account</th>
            <th style="width: 10%;">Payee</th>
            <th style="width: 10%;">Category</th>
            <th style="width: 7%;">Date</th>
            <th style="width: 30%;">Description</th>
            <th style="width: 8%;text-align: right!important;">Credit</th>
            <th style="width: 8%;text-align: right!important;">Debit</th>
            <th style="width: 8%;text-align: right!important;">Balance</th>
            <th style="width: 9%;text-align: right!important;">Actions</th>
          </tr>
        </thead>
        <%ImportedTransaction.all.each do |txn|%>
          <tr>
            <td style="width: 10%;padding-left: 5px !important;">
              <% if txn.flagged? %>
                <span style="color: #a94442;" class="glyphicon glyphicon-flag"></span>
              <%end%>
              <%if txn.payee.nil?%>
                <span style="color: #a94442;" class="glyphicon glyphicon-exclamation-sign"></span>
              <%else%>
                &nbsp;&nbsp;&nbsp;&nbsp;
              <%end%>
              &nbsp;<%=txn.account.name unless txn.account.nil?%>
            </td>
            <td style="width: 10%;">
              <%if txn.payee.nil?%>
                <%=form_tag payees_select_payee_path(imported_txn_id: txn.id),{:remote => true, :id => "import_txn_#{txn.id}"} do%>
                  <%= select_tag "id", options_from_collection_for_select(Payee.order(:name).all, :id, :name),{ :prompt => "Select Payee...",:onchange => "$('#import_txn_#{txn.id}').submit();" }%>
                <%end%>
              <%else%>
                <%=txn.payee.name%>
              <%end%>
            </td>
            <td style="width: 10%;">
							<div id="imported_txn_category_row_<%=txn.id%>">
								<%unless txn.category.nil?%>
									<table style="background-color: transparent !important;">
										<tr>
                      <td style="width: 90%; padding:0px !important;">&nbsp;<%=txn.category.name%></td>
											<td style="width: 10%;padding:0px !important;">
												<div class="actions">
													<%= link_to raw("<span class='fa fa-edit text-primary fa-lg'></span>"),
				                   edit_transaction_category_path(id: txn.category.id,imported_txn_id: txn.id), {:remote => true} %>
												</div>
											</td>
										</tr>
									</table>
								<%end%>
							</div>
            </td>
            <td style="width: 7%;"><%=txn.txn_date%></td>
            <td style="width: 30%;"><%=txn.description%></td>
            <td style="width: 8%;text-align: right;"><%=number_to_currency(txn.credit, precision: 2)%></td>
            <td style="width: 8%;text-align: right;"><%=number_to_currency(txn.debit, precision: 2)%></td>
            <td style="width: 8%;text-align: right;"><%=number_to_currency(txn.balance, precision: 2)%></td>
            <td style="width: 9%;">
              <div class="actions">
                <%if txn.payee.nil?%>
                  <%= link_to raw("<span class='fa fa-user fa-lg text-primary'></span>"),
                   new_payee_path(imported_txn_id: txn.id,called_from_import_txn: true), {:remote => true, class: 'new_payee-modal-link'} %>
                <%end%>
                <%= link_to raw("<span class='fa fa-exchange fa-lg text-primary'></span>"),
                 transfer_imported_transaction_path(txn.id), {:remote => true, class: 'new_payee-modal-link'} %>
                <%unless txn.payee.nil?%>
                 <%= link_to raw("<span class='fa fa-random fa-lg text-primary'></span>"),split_imported_transaction_path(txn.id), {:remote => true} %>
                <%end%>
                <%= link_to raw("<span class='fa fa-tags fa-lg text-primary'></span>"),tags_imported_transaction_path(txn.id), {:remote => true} %>
                <% if txn.flagged? %>
                  <%= link_to raw("<span class='fa fa-flag-o fa-lg text-danger'></span>"),flag_imported_transaction_path(txn.id), {:remote => true} %>
                <%else%>
                  <%= link_to raw("<span class='fa fa-flag-o fa-lg text-primary'></span>"),flag_imported_transaction_path(txn.id), {:remote => true} %>
                <%end%>
                <%= link_to raw("<span class='fa fa-trash-o fa-lg text-primary'></span>"), destroy_imported_transaction_path(txn.id), method: :delete, data: { confirm: 'Are you sure?' , :remote => true}%>
              </div>
            </td>
          </tr>
          <tr id=<%=txn.id.to_s + '_details'%> style="display:none;">
            <td style="width: 10%;">&nbsp;<%=txn.account.name unless txn.account.nil?%></td>
            <td style="width: 10%;">
              <%unless txn.payee.nil?%>
                <%=txn.payee.name%>
              <%end%>
            </td>
            <td style="width: 10%;">
              <%unless txn.category.nil?%>
                &nbsp;<%=txn.category.name%><
              <%end%>
            </td>
            <td style="width: 7%;"><%=txn.txn_date%></td>
            <td style="width: 30%;"><%=txn.description%></td>
            <td style="width: 8%;text-align: right!important;"><%=number_to_currency(txn.credit, precision: 2)%></td>
            <td style="width: 8%;text-align: right!important;"><%=number_to_currency(txn.debit, precision: 2)%></td>
            <td style="width: 8%;text-align: right!important;"><%=number_to_currency(txn.balance, precision: 2)%></td>
            <td style="width: 9%;text-align: right!important;">Actions</td>
          </tr>
        <%end%>
      </table>
    </div>

  </div></div>
    <div class="row" id="import-preview-footer">
      <div class="col-md-1">
        <%= link_to "Cancel",import_transactions_cancel_path(), class: "btn btn-default", style: "height: 100%;"%>
      </div>
      <div class="col-md-10">
        <div id="import-totals-content">
          <table style="width:100%;height: 100%;">
            <tr>
              <td style="width: 15%;">Credit</td>
              <td>&nbsp;</td>
              <td style="width: 15%;">Debit</td>
              <td>&nbsp;</td>
              <td style="width: 15%">Balance</td>
              <td style="border-left: 1px dotted #333;">&nbsp;</td>
              <td style="width: 15%;">Due Amount</td>
              <td>&nbsp;</td>
              <td style="width: 15%;">Statement Balance</td>
              <td>&nbsp;</td>
              <td style="width: 15%;">Reconciled Amount</td>
            </tr>
            <tr style="font-size: 14px;">
              <td><%=number_to_currency(ImportedTransaction.all.sum(:credit), precision: 2)%></td>
              <td>-</td>
              <td><%=number_to_currency(ImportedTransaction.all.sum(:debit), precision: 2)%></td>
              <td>=</td>
              <td><%=number_to_currency(ImportedTransaction.all.sum(:debit) +ImportedTransaction.all.sum(:credit) , precision: 2)%></td>
              <td style="border-left: 1px dotted #333;">&nbsp;</td>
              <td><%=number_to_currency(ImportedTransaction.all.sum(:debit) +ImportedTransaction.all.sum(:credit) , precision: 2)%></td>
              <td>-</td>
              <td><%=number_to_currency(ImportedTransaction.first.balance , precision: 2)%></td>
              <td>=</td>
              <td>
                <%unless ImportedTransaction.first.balance.nil?%>
                <%=number_to_currency((ImportedTransaction.all.sum(:debit) +ImportedTransaction.all.sum(:credit))- ImportedTransaction.first.balance, precision: 2)%>
                <%end%>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <div class="col-md-1">
        <%= link_to "Import",import_transactions_import_path(), class: "btn btn-primary", style: "height: 100%;"%>
      </div>
    </div>
  <%end%>
</div>

app/views/import_transactions/_split.html.erb
<tr id=<%=@imported_transaction.id.to_s + '_details'%> >
  <td colspan="9" style="padding: 0px!important;">
    <%=form_tag add_split_imported_transaction_path(txn_id: @imported_transaction.id),{:remote => true} do%>
    <div class="row" style="padding: 10px 0px 10px 0px;background-color: #894550; background-image: linear-gradient(to bottom, #9a4e5a 0px, #894550 100%);color: #ffffff;">
    <table class="col-md-12">
      <tr style="width: 100%;">
      	<td style="width: 9%;">
      		<%=@imported_transaction.account.name%>
      	</td>
        <td style="width: 10%;">
      		<%=@imported_transaction.payee.name%>
      	</td>
        <td style="width: 10%;color: #333;"><%= select_tag "category_id", options_from_collection_for_select(Category.all, :id, :name,@imported_transaction.category.id),{ :prompt => "Select Category..."}%></td>
        <td style="width: 6%;"><%=@imported_transaction.txn_date%></td>
        <td style="width: 33%;"><%= @imported_transaction.description%></td>
        <%unless @imported_transaction.credit.nil?%>
          <td style="width: 8%;color: #333;"><%=number_field_tag 'credit', @imported_transaction.credit, min: 1, max: @imported_transaction.credit.to_i%></td>
        <%else%>
          <td style="width: 8%;">&nbsp;</td>
        <%end%>
        <%unless @imported_transaction.debit.nil?%>
          <td style="width: 8%;color: #333;"><%=number_field_tag 'debit', @imported_transaction.debit, min: @imported_transaction.debit.to_i, max: -1%></td>
        <%else%>
          <td style="width: 8%;">&nbsp;</td>
        <%end%>
        <td style="width: 5%;">&nbsp;</td>
        <td style="width: 5%;">
          <button type="submit" style="background:none!important;border:none; "><i class="fa fa-random fa-lg"></i></button>
          <a href="#" id="<%=@imported_transaction.id.to_s + '_close'%>"><span style="color: white;" class="fa fa-times fa-lg"></span></a>
      	</td>
      </tr>
    </table>
  </div>
    <%end%>
  </td>
</tr>

<script>
$(function() {
  var btn_id = "#<%= escape_javascript@imported_transaction.id.to_s%>"+"_close";
  var tr_id = "#<%= escape_javascript@imported_transaction.id.to_s%>"+"_details";
  $(btn_id).click(function(event){
	$(tr_id).hide();
  });
});
</script>

app/views/import_transactions/_tags.html.erb
<!-- Modal -->
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h4 class="modal-title" id="tagsImportedTxnModalLabel">Tags for Transaction</h4>
		</div>

		<div class="modal-body">
			<%=form_tag add_tags_imported_transaction_path(txn_id: @imported_transaction.id),{:remote => true} do%>
			<div class="panel panel-default">
				<div class="panel-body">
						<h3><span class="fa fa-tags"></span> Add Tags</h3>
						<p>Add tags to transaction.</p>
				</div>

				<div class="panel-body form-group-separated">
						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Tags</label>
								<div class="col-md-9 col-xs-7">
										<%= text_field_tag :tags, @imported_transaction.tags, :data => {:role => 'tagsinput' }, class: "form-control" %>
								</div>
						</div>

						<div class="form-group">
								<div class="col-md-12 col-xs-5">
									<%= button_tag(type: 'submit',onclick: "$('#tagsImportedTxnModal').modal('hide');", class: "btn btn-primary btn-rounded pull-right") do %>
									 <i class='fa fa-tags'></i>&nbsp;Add Tags
									<% end %>
								</div>
						</div>
					</div>
				<%end%>
			</div>
		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</div>
</div>
<script>

  $(function() {
  	$("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput({
  		tagClass: 'label fa fa-tag'
  	});
  });
</script>

app/views/import_transactions/add_split.js.erb
$("#import-preview-pane").replaceWith("<%= escape_javascript(render '/import_transactions/preview') %>");

app/views/import_transactions/open_file.js.erb
$("#importTransactionsModal").html("<%= escape_javascript(render '/import_transactions/open_file') %>");
$('#importTransactionsModal').modal('show');

app/views/import_transactions/preview.js.erb
$("#import-preview-pane").replaceWith("<%= escape_javascript(render '/import_transactions/preview') %>");

app/views/import_transactions/process_file.html.erb
<div class="row" id="import-preview-container">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
					<h3 class="panel-title">Import Preview</h3>
					<ul class="panel-controls">
							<li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
					</ul>
			</div>

		  <% if flash[:error]%>
		    <div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		      <h2><strong>Warning!</strong> An error prohibited this import from being saved:</h2>
		      <ul>
		        <li><%= flash[:error]%></li>
		      </ul>
		    </div>
			<%end%>

			<%=render 'preview'%>
			<div class="modal fade" id="newPayeeModal" tabindex="-1" role="dialog" aria-labelledby="newPayeeModalLabel" aria-hidden="true"></div>
			<div class="modal fade" id="transferImportedTxnModal" tabindex="-1" role="dialog" aria-labelledby="transferImportedTxnModalLabel" aria-hidden="true"></div>
			<div class="modal fade" id="tagsImportedTxnModal" tabindex="-1" role="dialog" aria-labelledby="tagsImportedTxnModalLabel" aria-hidden="true"></div>
		</div>
	</div>
</div>