config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals
  match "goals/get_account_details" => "goals#get_account_details", :via => :post, :as => 'get_account_details'

  resources :shares
  match "shares/:id/sell_share" => "shares#sell_share", :via => :get, :as => 'sell_share'
  match "shares/:id/complete_share_sale" => "shares#complete_share_sale", :via => :patch, :as => 'complete_share_sale'

  resources :account_transactions

  resources :houses

  get 'tasks/calendar'

  resources :tasks do
    member do
      post :complete_task
      post :complete_task_widget
    end
  end

  get 'admin/index'

  get 'import_transactions/open_file'

  post 'import_transactions/process_file'

  match "import_transactions/:id" => "import_transactions#destroy", :via => :delete, :as => 'destroy_imported_transaction'

  match "import_transactions/:id/transfer" => "import_transactions#transfer", :via => :get, :as => 'transfer_imported_transaction'

  match "import_transactions/:id/update" => "import_transactions#update", :via => :patch, :as => 'imported_transaction'

  get 'import_transactions/import'

  get 'import_transactions/cancel'

  match "import_transactions/:id/split" => "import_transactions#split", :via => :get, :as => 'split_imported_transaction'
  match "import_transactions/add_split" => "import_transactions#add_split", :via => :post, :as => 'add_split_imported_transaction'

  match "import_transactions/:id/tags" => "import_transactions#tags", :via => :get, :as => 'tags_imported_transaction'
  match "import_transactions/add_tags" => "import_transactions#add_tags", :via => :post, :as => 'add_tags_imported_transaction'

  match "import_transactions/:id/flag" => "import_transactions#flag", :via => :get, :as => 'flag_imported_transaction'

  resources :budget_transactions
  match "budget_transactions/:id/edit_budget_item_transaction" => "budget_transactions#edit_budget_item_transaction", :via => :get, :as => 'edit_budget_item_transaction'
  match "budget_transactions/:id/update_cleared_status" => "budget_transactions#update_cleared_status", :via => :get, :as => 'update_cleared_status'
  get 'tags/:tag/:budget_id', to: 'budget_transactions#index', as: :tag
  match "search" => "budget_transactions#index", :via => :post, as: :search

  resources :payees
  post 'payees/select_payee'

  resources :budget_incomes
  match "budget_incomes/:id/show_income_splits" => "budget_incomes#show_income_splits", :via => :get, :as => 'show_income_splits'
  match "budget_incomes/:id/generate_income_splits" => "budget_incomes#generate_income_splits", :via => :post, :as => 'generate_income_splits'

  resources :incomes

  resources :accounts

  resources :account_types

  resources :budgets do
    member do
      post :update_progress
      get :close
    end
  end
  match "budgets/show_or_create/:month" => "budgets#show_or_create", :via => :get, :as => 'show_or_create_budget'

  resources :budget_items, :only => [:edit,:show,:update]
  match "budget_items/:id/one_click_transaction" => "budget_items#one_click_transaction", :via => :post, :as => 'one_click_transaction'

  resources :dashboard, :only => [:index]

  resources :categories
  match "categories/:id/edit_transaction_category" => "categories#edit_transaction_category", :via => :get, :as => 'edit_transaction_category'
  post 'categories/select_transaction_category'

  resources :master_categories

  get 'loans/index'

  get 'reports/index'
  get 'reports/category_report'
  get 'reports/master_category_report'
  get 'reports/payee_report'
  get 'reports/budget_expense_report'
  get 'reports/timeline'

  root 'dashboard#index'

end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :master_category
  has_many :budget_items

  validates_presence_of :name, :master_category_id, :budget_amount
  validates_uniqueness_of :name

  ##################################
  # Scoped Methods
  ##################################
  scope :non_system, -> { where('active = ?',true)}
  scope :for_budget, -> { where('active = ? and budgeted = ?',true,true)}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "admin", only: [:index, :new, :edit,:create,:update]
  before_action :set_category, only: [:show, :edit, :update, :destroy,:edit_transaction_category,:select_transaction_category]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.non_system
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_transaction_category
    @txn = ImportedTransaction.find(params[:imported_txn_id])
  end

  def select_transaction_category
    respond_to do |format|
      unless params[:imported_txn_id].nil?
        imported_txn = ImportedTransaction.find(params[:imported_txn_id])
        imported_txn.update(category_id: @category.id)
        format.js { render '/import_transactions/preview'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :icon, :active, :budget_amount,:master_category_id,:mandatory,:budgeted,:miscellaneous,:savings,:direct_debit, :scheduled, :scheduled_day,:has_template_transaction,:account_id,:payee_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit_transaction_category.html.erb
<%=form_tag categories_select_transaction_category_path(imported_txn_id: @txn.id),{:remote => true, :id => "import_txn_category_#{@txn.id}"} do%>
  <%= select_tag "id", options_from_collection_for_select(Category.all, :id, :name,@category.id),{ :prompt => "Select Category...",:onchange => "$('#import_txn_category_#{@txn.id}').submit();" }%>
<%end%>

app/views/categories/_form.html.erb
<!-- START ALERTS -->
<% if @category.errors.any? %>
  <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong>Warning!</strong> <%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:
      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  </div>
<%end%>
<!-- END ALERTS -->

<%= form_for(@category,html: {class: "form-horizontal"}) do |f| %>
<div class="panel-body">

  <div class="form-group">
      <%= f.label :name, {class: "col-md-3 col-xs-12 control-label"}%>
      <div class="col-md-6 col-xs-12">
          <div class="input-group">
              <span class="input-group-addon"><span class="fa fa-credit-card"></span></span>
              <%= f.text_field :name, {class: "form-control"} %>
          </div>
          <span class="help-block">Category name</span>
      </div>
  </div>

  <div class="form-group">
      <label class="col-md-3 col-xs-12 control-label">Icon</label>

      <div class="col-md-5 col-xs-12">
        <!-- own select -->
        <select name="category[icon]" id="icons-fa" class="fa-select form-control select">
          <%=render "category_icons"%>
        </select>

        <!-- Simple jq script for show selected item -->
        <script>
          $(document).ready(function(){
                /* Detect any change of option*/
          	$("#icons-fa").change(function(){
          		var icono = $(this).val();
          		$("#view-fa").html('<i class="fa '+icono+' fa-lg"></i>');
          	});

                 /* simulate an change on select */
          	$("#icons-fa").change();
          });
        </script>

        <span class="help-block">Select icon for this category</span>
      </div>
      <div class="col-md-1 col-xs-12">
        <!-- Make an div for show icon-->
        <span id="view-fa"></span><br/>
      </div>
  </div>

  <div class="form-group">
      <%= f.label :budget_amount, {class: "col-md-3 col-xs-12 control-label"}%>
      <div class="col-md-6 col-xs-12">
          <div class="input-group">
              <span class="input-group-addon"><span class="fa fa-dollar"></span></span>
              <%= f.number_field :budget_amount, class: "form-control",step: :any %>
          </div>
          <span class="help-block">The amount allocated per month</span>
      </div>
  </div>

<div class="form-group">
    <label class="col-md-3 col-xs-12 control-label">Master Category</label>
    <div class="col-md-6 col-xs-12">
      <% if f.object.persisted?%>
        <%= f.select "master_category_id", options_from_collection_for_select(MasterCategory.all.non_system, :id, :name,@category.master_category.id),{ :prompt => "Select Master Category..."},{ class: "form-control select"}%>
      <%else%>
        <%= f.select "master_category_id", options_from_collection_for_select(MasterCategory.all.non_system, :id, :name),{ :prompt => "Select Master Category..."},{ class: "form-control select"}%>
      <%end%>
      <span class="help-block">Select master category for this category</span>
    </div>
</div>

<div class="form-group">
    <%= f.label :mandatory, {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
      <label class="check">
          <%= f.radio_button :mandatory, true, {class: "iradio"}-%>
          True
      </label>
      <label class="check">
          <%= f.radio_button :mandatory, false,{class: "iradio"}-%>
          False
      </label>
      <span class="help-block">Required for display on the budget sheet</span>
    </div>
</div>

<div class="form-group">
    <%= f.label "Display Category", {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
      <span class="help-block">Budgeted</span>
      <label class="check">
          <%= f.radio_button :budgeted, true, {class: "iradio", id: "category-radio-budgeted-true"}-%>
          True
      </label>
      <label class="check">
          <%= f.radio_button :budgeted, false,{class: "iradio", id: "category-radio-budgeted-false"}-%>
          False
      </label>
      <span class="help-block">Miscellaneous</span>
      <label class="check">
          <%= f.radio_button :miscellaneous, true,{class: "iradio", id: "category-radio-misc-true"}-%>
          True
      </label>
      <label class="check">
          <%= f.radio_button :miscellaneous, false,{class: "iradio", id: "category-radio-misc-false"}-%>
          False
      </label>
      <span class="help-block">Savings</span>
      <label class="check">
          <%= f.radio_button :savings, true, {class: "iradio", id: "category-radio-savings-true"}-%>
          True
      </label>
      <label class="check">
          <%= f.radio_button :savings, false,{class: "iradio", id: "category-radio-savings-false"}-%>
          False
      </label>
      <br/><br/>
      <span class="help-block">Required for display on the budget sheet</span>
    </div>
</div>

<div class="form-group">
    <%= f.label "Direct Debit", {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
      <label class="check">
          <%= f.radio_button :direct_debit, true, {class: "iradio"}-%>
          True
      </label>
      <label class="check">
          <%= f.radio_button :direct_debit, false,{class: "iradio"}-%>
          False
      </label>
      <span class="help-block">Does the category have a potential Direct Debit Transaction?</span>
    </div>
</div>

<hr>
<div class="form-group">
    <span class="fa fa-calendar col-md-3 col-xs-12" style="text-align: right;"></span>

    <div class="col-md-9 col-xs-12">
        <%= f.label "Scheduled Transaction for Category", class: "control-label"%>
    </div>
</div>

<div class="form-group">
    <%= f.label "Scheduled Transactions", {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
      <label class="check">
          <%= f.radio_button :scheduled, true, {class: "iradio"}-%>
          True
      </label>
      <label class="check">
          <%= f.radio_button :scheduled, false,{class: "iradio"}-%>
          False
      </label>
      <span class="help-block">Does the category have a monthly scheduled Transaction?</span>
    </div>
</div>

<div class="form-group">
    <%= f.label :scheduled_day, {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
        <div class="input-group">
            <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
            <%= f.number_field :scheduled_day, class: "form-control",step: :any, max: 31 %>
        </div>
        <span class="help-block">The day every month when this category will have a scheduled transaction</span>
    </div>
</div>

<hr>
<div class="form-group">
    <span class="fa fa-hand-o-up col-md-3 col-xs-12" style="text-align: right;"></span>

    <div class="col-md-9 col-xs-12">
        <%= f.label "1-Click Template Transaction for Category", {class: "control-label"}%>
    </div>
</div>

<div class="form-group">
    <%= f.label "Template Transaction", {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
      <label class="check">
          <%= f.radio_button :has_template_transaction, true, {class: "iradio"}-%>
          True
      </label>
      <label class="check">
          <%= f.radio_button :has_template_transaction, false,{class: "iradio"}-%>
          False
      </label>
      <span class="help-block">Does the category have a potential 1-click template Transaction?</span>
    </div>
</div>

<div class="form-group">
    <%= f.label "Debit account", {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
      <div class="input-group">
          <%= f.collection_select :account_id, Account.active, :id, :name, {prompt: true}, {class: "form-control select"} %>
      </div>
      <span class="help-block">The account to debit for the 1-click transaction</span>
    </div>
</div>


<div class="form-group">
    <%= f.label "Payee account", {class: "col-md-3 col-xs-12 control-label"}%>
    <div class="col-md-6 col-xs-12">
      <div class="input-group">
          <%= f.collection_select :payee_id, Payee.non_system, :id, :name, {prompt: true}, {class: "form-control select"} %>
      </div>
      <span class="help-block">The Payee to credit for the 1-click transaction</span>
    </div>
</div>

</div>
<div class="panel-footer">
    <%= link_to 'Back', categories_path, {class: "btn btn-default"} %>
    <%= f.submit nil, {class: "btn btn-success pull-right"} %>
</div>

<% end %>

app/views/categories/_right_content_panel.html.erb
<div class="content-frame-right" style="height: 786px;">
  <div class="">
    <h4>Category Description</h4>
  </div>
  <div class="">
    <p>Categories are used to put expenses in buckets for identifying spending patterns.</p>
    <p>Mandatory categories which are budgeted are used to create recurring budget categories for every month to which transactions or expenses are associated. This helps define a budget for the month. The following provides some information regarding the various elements required to create a Category.</p>
    <p>
      <ul>
        <li>Name: The name to uniquely identify the category</li>
        <li>Budget: The amount budgeted for every month. Can be zero.</li>
        <li>Master Category: The parent classification bucket.</li>
        <li>Mandatory: If mandatory, the category is displayed along with the budget in either of the three display categories defined below</li>
        <li>Budgeted: To be displayed in the budgeted list</li>
        <li>Misc: To be displayed in the Miscellaneous list</li>
        <li>Savings: To be displayed in the savings list</li>
      </ul>
    </p>
  </div>
</div>

app/views/categories/edit.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
  <li><%=link_to "Admin",admin_index_path -%></li>
  <li><%=link_to "Categories",categories_path -%></li>
  <li class="active">Edit <%=@category.name-%></li>
</ul>
<!-- END BREADCRUMB -->

<div class="content-frame">

  <!-- START PAGE HEAD -->
  <div class="content-frame-top">
    <div class="page-title">
      <h2><span class="fa fa-tags"></span> Edit Category</h2>
    </div>
    <div class="pull-right">
    </div>
  </div>
  <!-- END PAGE HEAD -->

  <%= render 'right_content_panel' %>

  <div class="content-frame-body content-frame-body-left" style="height: 846px;">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Category: <%=@category.name-%></h3>
        <ul class="panel-controls">
          <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
          <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/edit_transaction_category.js.erb
var tr_id = "#imported_txn_category_row_<%= escape_javascript@txn.id.to_s%>"
$(tr_id).replaceWith("<%= escape_javascript(render '/categories/edit_transaction_category',:locals => {:obj => @category}) %>");

app/views/categories/index.html.erb
<!-- START ALERTS -->
<%=render 'layouts/alerts'-%>
<!-- END ALERTS -->

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
  <li><%=link_to "Admin",admin_index_path -%></li>
  <li class="active">Categories</li>
</ul>
<!-- END BREADCRUMB -->

<div class="content-frame">

  <!-- START PAGE HEAD -->
  <div class="content-frame-top">
    <div class="page-title">
      <h2><span class="fa fa-tags"></span> Categories</h2>
    </div>
    <div class="pull-right">
      <%= link_to raw("<span class='fa fa-plus'></span> New"), new_category_path, class: "btn btn-success btn-rounded" %>
    </div>
  </div>
  <!-- END PAGE HEAD -->

  <%= render 'right_content_panel' %>

  <div class="content-frame-body content-frame-body-left" style="height: 846px;">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">List of Categories</h3>
        <ul class="panel-controls">
          <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
          <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>
      </div>
      <div class="panel-body panel-body-table">
        <div class="table-responsive">
          <table class="table table-bordered table-striped table-actions table-hover">
            <thead>
                <tr>
                    <th width="50">Id</th>
                    <th>Name</th>
                    <th width="100">Budget</th>
                    <th width="100">Master Catgory</th>
                    <th width="100">Mandatory</th>
                    <th width="100">Budgeted</th>
                    <th width="100">Misc</th>
                    <th width="100">Savings</th>
                    <th width="120">actions</th>
                </tr>
            </thead>
            <tbody>
              <% @categories.each_with_index do |category,index| %>
                <tr id="trow_<%=index+1-%>">
                  <td class="text-center"><%=category.id-%></td>
                  <td><span class="fa <%=category.icon-%>">&nbsp;</span><%= category.name %></td>
                  <td class="table-right"><%= number_to_currency(category.budget_amount) %></td>
                  <td><%= category.master_category.name %></td>
                  <td class="table-center">
                      <% if category.mandatory %>
                        <span class="fa fa-check-square-o"></span>
                      <%else%>
                        <span class="fa fa-times"></span>
                      <%end%>
                  </td>
                  <td class="table-center">
                      <% if category.budgeted %>
                        <span class="fa fa-check-square-o"></span>
                      <%else%>
                        <span class="fa fa-times"></span>
                      <%end%>
                  </td>
                  <td class="table-center">
                      <% if category.miscellaneous %>
                        <span class="fa fa-check-square-o"></span>
                      <%else%>
                        <span class="fa fa-times"></span>
                      <%end%>
                  </td>
                  <td class="table-center">
                      <% if category.savings %>
                        <span class="fa fa-check-square-o"></span>
                      <%else%>
                        <span class="fa fa-times"></span>
                      <%end%>
                  </td>
                  <td>
                    <%= link_to raw("<span class='fa fa-pencil'></span>"), edit_category_path(category), :class=>"btn btn-default btn-rounded btn-condensed btn-sm" %>
                    <!-- <%= link_to raw("<span class='fa fa-times'></span>"), category, class: "btn btn-danger btn-rounded btn-condensed btn-sm", method: :delete, data: { confirm: 'Are you sure?'}, onClick: "delete_row('trow_#{index+1}');"%> -->
                 </td>
               </tr>
              <% end %>
            </tbody>
          </table>
      </div>

      </div>

    </div>

  </div>
</div>

app/views/categories/new.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
  <li><%=link_to "Admin",admin_index_path -%></li>
  <li><%=link_to "Categories",categories_path -%></li>
  <li class="active">New Category</li>
</ul>
<!-- END BREADCRUMB -->

<div class="content-frame">

  <!-- START PAGE HEAD -->
  <div class="content-frame-top">
    <div class="page-title">
      <h2><span class="fa fa-tags"></span> New Category</h2>
    </div>
    <div class="pull-right">
    </div>
  </div>
  <!-- END PAGE HEAD -->

  <%= render 'right_content_panel' %>

  <div class="content-frame-body content-frame-body-left" style="height: 846px;">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Category</h3>
        <ul class="panel-controls">
          <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
          <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @category.active %>
</p>

<p>
  <strong>Budget amount:</strong>
  <%= @category.budget_amount %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>