config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals
  match "goals/get_account_details" => "goals#get_account_details", :via => :post, :as => 'get_account_details'

  resources :shares
  match "shares/:id/sell_share" => "shares#sell_share", :via => :get, :as => 'sell_share'
  match "shares/:id/complete_share_sale" => "shares#complete_share_sale", :via => :patch, :as => 'complete_share_sale'

  resources :account_transactions

  resources :houses

  get 'tasks/calendar'

  resources :tasks do
    member do
      post :complete_task
      post :complete_task_widget
    end
  end

  get 'admin/index'

  get 'import_transactions/open_file'

  post 'import_transactions/process_file'

  match "import_transactions/:id" => "import_transactions#destroy", :via => :delete, :as => 'destroy_imported_transaction'

  match "import_transactions/:id/transfer" => "import_transactions#transfer", :via => :get, :as => 'transfer_imported_transaction'

  match "import_transactions/:id/update" => "import_transactions#update", :via => :patch, :as => 'imported_transaction'

  get 'import_transactions/import'

  get 'import_transactions/cancel'

  match "import_transactions/:id/split" => "import_transactions#split", :via => :get, :as => 'split_imported_transaction'
  match "import_transactions/add_split" => "import_transactions#add_split", :via => :post, :as => 'add_split_imported_transaction'

  match "import_transactions/:id/tags" => "import_transactions#tags", :via => :get, :as => 'tags_imported_transaction'
  match "import_transactions/add_tags" => "import_transactions#add_tags", :via => :post, :as => 'add_tags_imported_transaction'

  match "import_transactions/:id/flag" => "import_transactions#flag", :via => :get, :as => 'flag_imported_transaction'

  resources :budget_transactions
  match "budget_transactions/:id/edit_budget_item_transaction" => "budget_transactions#edit_budget_item_transaction", :via => :get, :as => 'edit_budget_item_transaction'
  match "budget_transactions/:id/update_cleared_status" => "budget_transactions#update_cleared_status", :via => :get, :as => 'update_cleared_status'
  get 'tags/:tag/:budget_id', to: 'budget_transactions#index', as: :tag
  match "search" => "budget_transactions#index", :via => :post, as: :search

  resources :payees
  post 'payees/select_payee'

  resources :budget_incomes
  match "budget_incomes/:id/show_income_splits" => "budget_incomes#show_income_splits", :via => :get, :as => 'show_income_splits'
  match "budget_incomes/:id/generate_income_splits" => "budget_incomes#generate_income_splits", :via => :post, :as => 'generate_income_splits'

  resources :incomes

  resources :accounts

  resources :account_types

  resources :budgets do
    member do
      post :update_progress
      get :close
    end
  end
  match "budgets/show_or_create/:month" => "budgets#show_or_create", :via => :get, :as => 'show_or_create_budget'

  resources :budget_items, :only => [:edit,:show,:update]
  match "budget_items/:id/one_click_transaction" => "budget_items#one_click_transaction", :via => :post, :as => 'one_click_transaction'

  resources :dashboard, :only => [:index]

  resources :categories
  match "categories/:id/edit_transaction_category" => "categories#edit_transaction_category", :via => :get, :as => 'edit_transaction_category'
  post 'categories/select_transaction_category'

  resources :master_categories

  get 'loans/index'

  get 'reports/index'
  get 'reports/category_report'
  get 'reports/master_category_report'
  get 'reports/payee_report'
  get 'reports/budget_expense_report'
  get 'reports/timeline'

  root 'dashboard#index'

end

app/models/payee.rb
class Payee < ApplicationRecord
  attr_accessor :called_from_import_txn

  ##################################
  # Relationships
  ##################################
  has_many :budget_transactions
  belongs_to :category
  belongs_to :account
  has_many :payee_descriptions

  ##################################
  # Validations
  ##################################
  validates_uniqueness_of :name
  validates_uniqueness_of :account_id, :allow_nil => true
  validates_presence_of :name, :description, :category_id
  validates_presence_of :account_id, if: :is_account?
  validates_numericality_of :account_id, :allow_nil => true

  ##################################
  # Callbacks
  ##################################

  ##################################
  # Scoped Methods
  ##################################
  scope :external_payees, -> { where('is_system = ? && is_account = ?',false,false)}
  scope :all_account_payees, -> { where('is_system = ? && is_account = ?',false,true)}
  scope :account_payees, -> { joins(:account).where('is_account = ? AND accounts.is_active = ? AND accounts.budget_account = ?',true,true,true)}
  scope :loan_account_payees, -> { joins(account: :account_type).where('is_account = ? AND accounts.is_active = ? AND account_types.name = ?',true,true,"Loan")}
  scope :all_account_payees, -> { joins(:account).where('is_account = ? AND accounts.is_active = ?',true,true)}
  scope :system_payees, -> { where(is_system: true)}
  scope :non_system, -> { where(is_system: false)}
  scope :transfer_account_payees, -> { joins(account: :account_type).where('is_account = ? AND accounts.is_active = ? AND (account_types.name = ? OR account_types.name = ? OR account_types.name = ? OR account_types.name = ? OR account_types.name = ?)',true,true,"Transaction","Savings","Credit","Offset","Brokerage")}
  scope :non_credit_account_payees, -> { joins(account: :account_type).where('is_account = ? AND accounts.is_active = ? AND accounts.budget_account = ? AND account_types.name = ?',true,true,true,"Transaction")}
  ##################################
  # Class Methods
  ##################################
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
  layout "admin", only: [:index, :new, :edit,:create,:update]
  before_action :set_payee, only: [:show, :edit, :update, :destroy,:select_payee]

  # GET /payees
  # GET /payees.json
  def index
    @external_payees = Payee.external_payees
    @account_payees = Payee.all_account_payees
  end

  # GET /payees/1
  # GET /payees/1.json
  def show
  end

  # GET /payees/new
  def new
    @payee = Payee.new
    @payee.called_from_import_txn = params[:called_from_import_txn]

    unless params[:imported_txn_id].nil?
      imported_txn = ImportedTransaction.find(params[:imported_txn_id])
      @payee.description = imported_txn.description
    end
  end

  # GET /payees/1/edit
  def edit
  end

  # POST /payees
  # POST /payees.json
  def create
    @payee = Payee.new(payee_params)

    if @payee.called_from_import_txn == "true"
      respond_to do |format|
        if @payee.save
          ImportedTransaction.where('description = ? ', @payee.description).update_all(payee_id: @payee.id,category_id: @payee.category.id)
          format.js
        end
      end
    else
      respond_to do |format|
        if @payee.save
          @imported_transactions = ImportedTransaction.all
          format.html { redirect_back(fallback_location: budgets_path)}
          format.json { render :show, status: :created, location: @payee }
          format.js
        else
          format.html { render :new }
          format.json { render json: @payee.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end
  end

  # PATCH/PUT /payees/1
  # PATCH/PUT /payees/1.json
  def update
    respond_to do |format|
      if @payee.update(payee_params)
        format.html { redirect_to payees_url, notice: 'Payee was successfully updated.' }
        format.json { render :show, status: :ok, location: @payee }
      else
        format.html { render :edit }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payees/1
  # DELETE /payees/1.json
  def destroy
    @payee.destroy
    respond_to do |format|
      format.html { redirect_to payees_url, notice: 'Payee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_payee
      respond_to do |format|
        unless params[:imported_txn_id].nil?
          imported_txn = ImportedTransaction.find(params[:imported_txn_id])
          payee_description = PayeeDescription.new(:description => imported_txn.description, :payee_id => @payee.id)

          if payee_description.save!
            ImportedTransaction.where('description = ? ', payee_description.description).update_all(payee_id: @payee.id,category_id: @payee.category.id)
            format.js { render '/import_transactions/preview', layout: "application"}
          end
        end
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payee
      @payee = Payee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payee_params
      params.require(:payee).permit(:name, :description, :category_id,:is_account,:is_system,:account_id,:called_from_import_txn)
    end
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/views/payees/_form.html.erb
<!-- START ALERTS -->
<% if @payee.errors.any? %>
  <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong>Warning!</strong> <%= pluralize(@payee.errors.count, "error") %> prohibited this category from being saved:
      <ul>
      <% @payee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  </div>
<%end%>
<!-- END ALERTS -->

<%= form_for(@payee,html: {class: "form-horizontal"}) do |f| %>
<div class="panel-body">

  <div class="form-group">
      <%= f.label :name, {class: "col-md-3 col-xs-12 control-label"}%>
      <div class="col-md-6 col-xs-12">
          <div class="input-group">
              <span class="input-group-addon"><span class="fa fa-credit-card"></span></span>
              <%= f.text_field :name, {class: "form-control"} %>
          </div>
          <span class="help-block">External payee name</span>
      </div>
  </div>

  <div class="form-group">
      <%= f.label :description, {class: "col-md-3 col-xs-12 control-label"}%>
      <div class="col-md-6 col-xs-12">
          <div class="input-group">
              <span class="input-group-addon"><span class="fa fa-align-justify"></span></span>
              <%= f.text_field :description, {class: "form-control"} %>
          </div>
          <span class="help-block">The generic description for the payee</span>
      </div>
  </div>
  <% unless f.object.persisted?%>
  <div class="form-group">
      <label class="col-md-3 col-xs-12 control-label">Select</label>
      <div class="col-md-6 col-xs-12">
        <%= f.select "category_id", options_from_collection_for_select(Category.all.non_system, :id, :name),{ :prompt => "Select Category..."},{ class: "form-control select"}%>
        <span class="help-block">The category the payee belongs to</span>
      </div>
  </div>
  <%end%>
  <hr>

  <% if f.object.persisted?%>
  <div class="form-group">
      <span class="fa fa-align-justify col-md-3 col-xs-12" style="text-align: right;"></span>

      <div class="col-md-9 col-xs-12">
          <%= f.label "Additional Payee Descriptions", {class: "control-label"}%>
      </div>
  </div>

  <div class="form-group">
      <%unless @payee.payee_descriptions.count < 1%>
      <%= f.label "Payee Descriptions", {class: "col-md-3 col-xs-12 control-label"}%>
      <div class="col-md-9 col-xs-12">
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
                <tr>
                    <th width="50">id</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <%@payee.payee_descriptions.each_with_index do |payee_description,index| %>
                <tr id="trow_<%=index+1-%>">
                  <td class="text-center"><%=index+1-%></td>
                  <td><%=payee_description.description%></td>
               </tr>
               <%end%>
            </tbody>
          </table>
        </div>
        <span class="help-block">Associated Payee Descriptions for merchant categorisation</span>
      </div>
      <%else%>
        <span class="col-md-3 col-xs-12" style="text-align: right;"></span>
        <div class="col-md-9 col-xs-12">
            There are no additional descriptions for this payee
        </div>
      <%end%>
    </div>

  <%end%>
</div>

<div class="panel-footer">
    <%= link_to 'Back', payees_path, {class: "btn btn-default"} %>
    <%= f.submit nil, {class: "btn btn-success pull-right"} %>
</div>

<% end %>

app/views/payees/_new.html.erb
<!-- Modal -->
<div class="modal-dialog">
	<div class="modal-content">

		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h4 class="modal-title" id="newPayeeModalLabel">New Payee</h4>
		</div>

		<div class="modal-body">
			<div class="panel panel-default">
				<div class="panel-body">
						<h3><span class="fa fa-pencil"></span> New Payee</h3>
						<p>Add a new Payee.</p>
				</div>
				<div class="panel-body form-group-separated">
						<%
							if @payee.called_from_import_txn == "true"
								is_remote = true
							else
								is_remote = false
							end
						%>
						
						<%= form_for @payee, remote: is_remote, html: {class: 'form-horizontal', role: :form} do |f| %>

						<%= f.hidden_field :is_account, :value => false%>
						<%= f.hidden_field :called_from_import_txn, :value => @payee.called_from_import_txn%>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Name</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group">
											<%= f.text_field :name, class: "form-control" %>
										</div>
								</div>
						</div>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Description</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group">
											<%= f.text_field :description, class: "form-control" %>
											<span class="input-group-addon"><span class="fa fa-comment"></span></span>
										</div>
								</div>
						</div>

						<div class="form-group">
								<label class="col-md-3 col-xs-5 control-label">Category</label>
								<div class="col-md-9 col-xs-7">
										<div class="input-group">
											<%= f.collection_select :category_id, Category.where('active = ?',true), :id, :name, {prompt: true}, {class: "form-control select"} %>
										</div>
								</div>
						</div>

						<div class="form-group">
								<div class="col-md-12 col-xs-5">
									<%= button_tag(type: 'submit', class: "btn btn-primary btn-rounded pull-right") do %>
									 <i class='fa fa-user'></i>&nbsp;Create Payee
									<% end %>
								</div>
						</div>

					<%end%>
				</div>
		</div>
		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>

	</div>

</div>

app/views/payees/_right_content_panel.html.erb
<div class="content-frame-right" style="height: 786px;">
  <div class="">
    <h4>Payee Description</h4>
  </div>
  <div class="">
    <p>Categories are used to put expenses in buckets for identifying spending patterns.</p>
    <p>Mandatory categories which are budgeted are used to create recurring budget categories for every month to which transactions or expenses are associated. This helps define a budget for the month. The following provides some information regarding the various elements required to create a Category.</p>
    <p>
      <ul>
        <li>Name: The name to uniquely identify the category</li>
        <li>Budget: The amount budgeted for every month. Can be zero.</li>
        <li>Master Category: The parent classification bucket.</li>
        <li>Mandatory: If mandatory, the category is displayed along with the budget in either of the three display categories defined below</li>
        <li>Budgeted: To be displayed in the budgeted list</li>
        <li>Misc: To be displayed in the Miscellaneous list</li>
        <li>Savings: To be displayed in the savings list</li>
      </ul>
    </p>
  </div>
</div>

app/views/payees/create.js.erb
$("#import-preview-pane").replaceWith("<%= escape_javascript(render '/import_transactions/preview') %>");
$('#newPayeeModal').modal('hide');

app/views/payees/edit.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
  <li><%=link_to "Admin",admin_index_path -%></li>
  <li><%=link_to "Payees",payees_path -%></li>
  <li class="active">Edit <%=@payee.name-%></li>
</ul>
<!-- END BREADCRUMB -->

<div class="content-frame">

  <!-- START PAGE HEAD -->
  <div class="content-frame-top">
    <div class="page-title">
      <h2><span class="fa fa-credit-card"></span> Edit Payee</h2>
    </div>
    <div class="pull-right">
    </div>
  </div>
  <!-- END PAGE HEAD -->

  <%= render 'right_content_panel' %>

  <div class="content-frame-body content-frame-body-left" style="height: 846px;">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Payee: <%=@payee.name-%></h3>
        <ul class="panel-controls">
          <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
          <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/payees/index.html.erb
<!-- START ALERTS -->
<%=render 'layouts/alerts'-%>
<!-- END ALERTS -->

<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
  <li><%=link_to "Admin",admin_index_path -%></li>
  <li class="active">Payees</li>
</ul>
<!-- END BREADCRUMB -->

<div class="content-frame">

  <!-- START PAGE HEAD -->
  <div class="content-frame-top">
    <div class="page-title">
      <h2><span class="fa fa-credit-card"></span> Payees</h2>
    </div>
    <div class="pull-right">
      <%= link_to raw("<span class='fa fa-plus'></span> New"), new_payee_path, class: "btn btn-success btn-rounded" %>
    </div>
  </div>
  <!-- END PAGE HEAD -->

  <%= render 'right_content_panel' %>

  <div class="content-frame-body content-frame-body-left" style="height: 846px;">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">List of External Payees</h3>
          <ul class="panel-controls">
            <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
          </ul>
        </div>
        <div class="panel-body panel-body-table">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-actions table-hover">
              <thead>
                  <tr>
                      <th width="50">id</th>
                      <th>name</th>
                      <th>Description</th>
                      <th>Category</th>
                      <th width="50">Aditional Descriptions</th>
                      <th width="50">actions</th>
                  </tr>
              </thead>
              <tbody>
                <% @external_payees.each_with_index do |payee,index| %>
                  <tr id="trow_<%=index+1-%>">
                    <td class="text-center"><%=index+1-%></td>
                    <td><%= payee.name %></td>
                    <td><%= payee.description %></td>
                    <td><%= payee.category.name %></td>
                    <td class="table-center">
                        <%= payee.payee_descriptions.count %>
                    </td>
                    <td>
                      <%= link_to raw("<span class='fa fa-pencil'></span>"), edit_payee_path(payee), :class=>"btn btn-default btn-rounded btn-condensed btn-sm" %>
                      <!-- <%= link_to raw("<span class='fa fa-times'></span>"), payee, class: "btn btn-danger btn-rounded btn-condensed btn-sm", method: :delete, data: { confirm: 'Are you sure?'}, onClick: "delete_row('trow_#{index+1}');"%> -->
                   </td>
                 </tr>
                <% end %>
              </tbody>
            </table>
        </div>
      </div>

    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">List of Account Payees</h3>
          <ul class="panel-controls">
            <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
          </ul>
        </div>
        <div class="panel-body panel-body-table">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-actions table-hover">
              <thead>
                  <tr>
                      <th width="50">id</th>
                      <th>name</th>
                      <th>Description</th>
                      <th>Category</th>
                      <th width="120">Account</th>
                  </tr>
              </thead>
              <tbody>
                <% @account_payees.each_with_index do |payee,index| %>
                  <tr id="trow_<%=index+1-%>">
                    <td class="text-center"><%=index+1-%></td>
                    <td><%= payee.name %></td>
                    <td><%= payee.description %></td>
                    <td><%= payee.category.name %></td>
                    <% if payee.is_account %>
                      <td>
                          <%= payee.account.name %>
                      </td>
                      <%else%>
                      <td class="table-center">
                          <span class="fa fa-times"></span>
                      </td>
                    <%end%>
                    <!-- <td>
                      <%= link_to raw("<span class='fa fa-pencil'></span>"), edit_payee_path(payee), :class=>"btn btn-default btn-rounded btn-condensed btn-sm" %>
                      <%= link_to raw("<span class='fa fa-times'></span>"), payee, class: "btn btn-danger btn-rounded btn-condensed btn-sm", method: :delete, data: { confirm: 'Are you sure?'}, onClick: "delete_row('trow_#{index+1}');"%>
                   </td> -->
                 </tr>
                <% end %>
              </tbody>
            </table>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/payees/new.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
  <li><%=link_to "Admin",admin_index_path -%></li>
  <li><%=link_to "Payees",payees_path -%></li>
  <li class="active">New Payee</li>
</ul>
<!-- END BREADCRUMB -->

<div class="content-frame">

  <!-- START PAGE HEAD -->
  <div class="content-frame-top">
    <div class="page-title">
      <h2><span class="fa fa-credit-card"></span> New Payee</h2>
    </div>
    <div class="pull-right">
    </div>
  </div>
  <!-- END PAGE HEAD -->

  <%= render 'right_content_panel' %>

  <div class="content-frame-body content-frame-body-left" style="height: 846px;">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Payee</h3>
        <ul class="panel-controls">
          <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
          <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/payees/new.js.erb
$("#newPayeeModal").html("<%= escape_javascript(render '/payees/new') %>");
$('#newPayeeModal').modal('show');

app/views/payees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payee.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @payee.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @payee.category_id %>
</p>

<%= link_to 'Edit', edit_payee_path(@payee) %> |
<%= link_to 'Back', payees_path %>